objtype=power64
</$objtype/mkfile

LIB=/$objtype/lib/libc.a
SFILES=\
	argv0.s\
	atom.s\
	atomic.s\
	atomic64.s\
	cycles.s\
	getcallerpc.s\
	getfcr.s\
	main9.s\
	main9p.s\
	setjmp.s\
	tas.s\

CFILES=\
	_seek.c\
	notejmp.c\

HFILES=/sys/include/libc.h

OFILES=${CFILES:%.c=%.$O} ${SFILES:%.s=%.$O}

</sys/src/cmd/mksyslib
